<a href="https://colab.research.google.com/github/Jayant8140/numpy_assignment/blob/main/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [ ]:
arr=np.arange(6)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5])

Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])

In [ ]:
arr = np.array([1.5, 2.6, 3.7])

In [ ]:
arr.dtype

dtype('float64')

 Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [ ]:
arr=np.array([1+2j,1+3j,1+4j],dtype=np.complex128)
print(arr)
print(arr.dtype)


[1.+2.j 1.+3.j 1.+4.j]
complex128


. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [ ]:
arr=np.array([1,2,3,4])

In [ ]:
arr.dtype



dtype('int64')

In [ ]:
arr=arr.astype(np.float32)#rr.astype(np.float32) converts the data type of the array to float32 using the astype method.
print(arr.dtype)

float32


 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [ ]:
arr=np.array([1.23455,2.45678,4.56789],dtype=np.float64)
arr=arr.astype(np.float32)
print(arr)
print(arr.dtype)

[1.23455 2.45678 4.56789]
float32


6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type

In [ ]:
def array_attribute(arr):
  return arr.shape,arr.size,arr.dtype


In [ ]:
arr=np.array([1,2,3,4,4,5])
shape,size,dtype=array_attribute(arr)
print("shape",shape)
print("size",size)
print("dtype",dtype)

shape (6,)
size 6
dtype int64


. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [ ]:
def array_dimension(arr):
  return arr.ndim

In [ ]:
arr=np.array([[1,2,3,4,4,5]])
dimension=array_dimension(arr)
print("dimension",dimension)



dimension 2


8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.

In [ ]:
def item_size_info(arr):
  item_size=arr.itemsize
  total_size=arr.nbytes
  return item_size,total_size

In [ ]:
arr=np.array([1,2,34,4,5,6])
item_size,total_size=item_size_info(arr)
print("item_size",item_size)
print("total_size",total_size)

item_size 8
total_size 48


9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [ ]:
def array_strides(arr):
  return arr.strides

In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
array_strides=array_strides(arr)
print(array_strides)

(32, 8)


 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array

In [ ]:
def shape_stride_relationship(arr):
  return arr.shape,arr.strides

In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
shape_stride_relationship(arr)

((2, 4), (32, 8))

 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements

In [ ]:
def create_zeros_array(n):
  return np.zeros(n)

In [ ]:
element=4
create_zeros_array(element)

array([0., 0., 0., 0.])

12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`

In [ ]:
def create_ones_matrix(rows,column):
  return np.ones((rows,column))

In [ ]:
rows=3
column=4
create_ones_matrix(rows,column)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.

In [ ]:
def generate_range_array(start,stop,step):
  return np.arange(start,stop,step)

In [ ]:
start=1
stop=40
step=6
generate_range_array(start,stop,step)

array([ 1,  7, 13, 19, 25, 31, 37])

 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive)

In [ ]:
def generate_linear_space(start,stop,num):
  return np.linspace(start,stop,num)

In [ ]:
start=1
stop=10
num=5
generate_linear_space(start,stop,num)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`

In [ ]:
def create_identity_matrix(n):
  return np.eye(n)

In [ ]:
n=4
create_identity_matrix(n)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

 16. Write a function that takes a Python list and converts it into a NumPy array.

In [ ]:
def my_first_list(list):
  return np.array(list)

In [ ]:
my_list=[1,2,34,5,6]
my_first_list(my_list)

array([ 1,  2, 34,  5,  6])

 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data

In [ ]:
original_data=np.array([1,2,3,4,5])
view_array=original_data.view()
view_array[0]=10
print(original_data)
print(view_array)

[10  2  3  4  5]
[10  2  3  4  5]


18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [ ]:
def concatenate_array(arr1,arr2,axis=1):
  return np.concatenate((arr1,arr2),axis=axis)

In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
concatenate_array(arr1,arr2)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
def concatenate_array(arr1,arr2,axis=0):
  return np.concatenate((arr1,arr2),axis=axis)

In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
concatenate_array(arr1,arr2)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

 19.  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
 concatenate`

In [ ]:
array1=np.array([1,2,3,4])
array2=np.array([[1,2,3,4],[5,6,7,8]])
array1_reshaped=array1.reshape(2,2)
np.concatenate((array1_reshaped,array2),axis=1)

array([[1, 2, 1, 2, 3, 4],
       [3, 4, 5, 6, 7, 8]])

In [ ]:
array1=np.array([1,2,3,4])
array1_reshaped=array1.reshape(2,2)
print(array1_reshaped)


[[1 2]
 [3 4]]


 20. Write a function that vertically stacks multiple NumPy arrays given as a list

In [ ]:
def vertical_stack(arr_list):
  return np.vstack(arr_list)

In [ ]:
arra1=np.array([1,2,3,4])
array2=np.array([2,3,45,6])
arr_list=[arra1,array2]
vertical_stack(arr_list)

array([[ 1,  2,  3,  4],
       [ 2,  3, 45,  6]])

 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size

In [ ]:
import numpy as np
def inclusive_arange(start,stop,step=2):
  num=int((stop-start)/step)+1
  arr=np.linspace(start,stop,num,dtype=int)
  return arr

In [ ]:
arr=inclusive_arange(1,10)

print(arr)

[ 1  3  5  7 10]


 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive)

In [ ]:
def generate_spaced_value(num_value=10):
  return np.linspace(0,1,num_value)

In [ ]:
generate_spaced_value(num_value=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive)

In [ ]:
import numpy as np
def log_values(start,stop,num):
  return np.logspace(np.log10(start),np.log10(stop),num)

In [ ]:
start=1
stop=100
num=5
log_value=log_values(start,stop,num)
print(log_value)

[  1.           3.16227766  10.          31.6227766  100.        ]


24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100

In [ ]:
import pandas as pd

In [ ]:
data=np.random.randint(1,101,size=(5,3))
df=pd.DataFrame(data,columns=['a','b','c'])
print(df)

    a   b   c
0  77  49  28
1  96   3   4
2  31  46  31
3  73  92  67
4  53  41  88


25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame

In [ ]:
def replace_negative_no(df,column_name):
   df[column_name]=np.where(df[column_name]<0,0,df[column_name])
   return df


In [ ]:
data= {'a':[1,2,3,4,5],'b':[-5,-6,-7,-8,9]}
df=pd.DataFrame(data)

replace_negative_no(df,'b')
print(df)

   a  b
0  1  0
1  2  0
2  3  0
3  4  0
4  5  9


26. Access the 3rd element from the given NumPy array.
 arr = np.array([10, 20, 30, 40, 50])

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
 arr_2d = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d[1,2]

6

28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
 arr = np.array([3, 8, 2, 10, 5, 7])

In [ ]:
arr = np.array([3, 8, 2, 10, 5, 7])

In [ ]:
greater_no=arr[arr>5]
print(greater_no)

[ 8 10  7]


 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
 arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
extract_element=arr[2:6]
print(extract_element)


[3 4 5 6]


 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
 arr_2d = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
sub_array=arr_2d[0:2,1:3]

In [ ]:
sub_array

array([[2, 3],
       [5, 6]])

31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.

In [ ]:
def extract_element_by_indices(arr_2d,indices):
  rows=indices[:,0]
  columns=indices[:,1]
  return arr_2d[rows,columns]


In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
indices=np.array([[0,1],[2,0],[1,2]])
extract_element=extract_element_by_indices(arr_2d,indices)
print(extract_element)

[2 7 6]


32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.

In [ ]:
def filter_threshold(arr,threshold):
  mask=arr>threshold
  filter_no=arr[mask]
  return filter_no

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])
threshold=5
filter=filter_threshold(arr,threshold)
print(filter)

[6 7 8 9]


33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension


In [ ]:
def extract_element(arr3d,indices_x,indices_y,indices_z):
  return arr3d[indices_x,indices_y,indices_z]

In [ ]:

arr_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                   [[7, 8, 9], [10, 11, 12]]])

In [ ]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
indices_x=([0,1])
indices_y=([1,0])
indices_z=([2,1])
extract=extract_element(arr_3d,indices_x,indices_y,indices_z)
print(extract)

[6 8]



34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing


In [ ]:
def filter_two_condition(arr,condition1,condition2):
  combined_condition=np.logical_and(condition1,condition2)#logical and operation check if both True
  filtered_array=arr[combined_condition]
  return filtered_array

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])
condition1=arr>4
condition2=arr%2==0
filter=filter_two_condition(arr,condition1,condition2)
print(filter)

[6 8]


35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.

In [ ]:
import numpy as np

In [ ]:
def extract_element1(arr,row_indices,column_indices):
  return arr[row_indices,column_indices]

In [ ]:

arr_2d = np.array([[1, 11, 3],
                   [70, 78, 56],
                   [7, 89, 90]])

In [ ]:
row_indices=np.array([0,2,1])
column_indices=np.array([1,0,2])
extract=extract_element1(arr_2d,row_indices,column_indices)
print(extract)

[11  7 56]


 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [ ]:
arr=np.array([[1,2,3],[5,6,7],[7,8,9]])
result=arr+5
print(result)

[[ 6  7  8]
 [10 11 12]
 [12 13 14]]


37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
result=arr1.reshape(3,1) * arr2
print(result)

[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting

In [ ]:
arr1=np.array([1,2,3,4])
arr2=([[1,2,3],[2,3,4],[4,5,6],[5,6,7]])
result=arr1.reshape(4,1)+arr2
print(result)

[[ 2  3  4]
 [ 4  5  6]
 [ 7  8  9]
 [ 9 10 11]]


 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting

In [ ]:
arr1=np.array([[1],[2],[3]])
arr2=np.array([1,2,3])
result=arr1+arr2
print(result)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.

In [ ]:
arr1 = np.array([[1, 2, 3],
                [4, 5, 6]])  # Shape (2, 3)
arr2 = np.array([[7, 8],
                [9, 10]])  # Shape (2, 2)


result=arr1*arr2[:,:,np.newaxis]
print(result)

[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


41. Calculate column-wise mean for the given array:
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
np.mean(arr,axis=0)

array([2.5, 3.5, 4.5])

 42. Find maximum value in each row of the given array:
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.max(arr,axis=1)

array([3, 6])

 43. For the given array, find indices of maximum value in each column.
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) #indicies = index at which the value is larger here [4,5,6] are at [1,1,1] index
np.argmax(arr,axis=0)

array([1, 1, 1])

45. In the given array, check if all elements in each column are even.
 arr = np.array([[2, 4, 6], [3, 5, 7]])

In [ ]:
arr = np.array([[2, 4, 6], [3, 5, 7]])
np.all(arr%2==0,axis=0)

array([False, False, False])

46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.
 original_array = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
original_array = np.array([1, 2, 3, 4, 5, 6])
m=3
n=2
reshaped_array=original_array.reshape(m,n)
print(reshaped_array)

[[1 2]
 [3 4]
 [5 6]]


47. Create a function that takes a matrix as input and returns the flattened array.
 input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
def faltten_matrix(matrix):
  return matrix.flatten()

In [ ]:
input_matrix=np.array([[1, 2, 3], [4, 5, 6]])
flatten_array=faltten_matrix(input_matrix)
print(flatten_array)

[1 2 3 4 5 6]


 48. Write a function that concatenates two given arrays along a specified axis.
 array1 = np.array([[1, 2], [3, 4]])
 array2 = np.array([[5, 6], [7, 8]])

In [ ]:
def concatinate_array(array1,array2,axis=0):
  return np.concatenate((array1,array2),axis=axis)

In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatinate_array(array1,array2,axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
 original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
def spli_array(arr,num_splits,axis=0):
  return np.split(arr,num_splits,axis=axis)

In [ ]:
original_array= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
horizontal=spli_array(original_array,3,axis=1)
vertical=spli_array(original_array,3,axis=0)
print(horizontal)
print(vertical)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


 50. Write a function that inserts and then deletes elements from a given array at specified indices.
 original_array = np.array([1, 2, 3, 4, 5])
 indices_to_insert = [2, 4]
 values_to_insert = [10, 11]
 indices_to_delete = [1, 3]

In [ ]:
original_array = np.array([1, 2, 3, 4, 5]) #(1,2,10,3,4,11,5)
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
def insert_delete_elements(arr,insert_array,insert_values,delete_values):
  arr=np.insert(arr,insert_array,insert_values)
  arr=np.delete(arr,delete_values)
  return arr



In [ ]:
insert_delete_elements(original_array,indices_to_insert,values_to_insert,indices_to_delete)

array([ 1, 10,  4, 11,  5])

 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

In [ ]:
arr1=np.random.randint(1,100,size=10)
arr2=np.arange(1,11)
print(arr1)
print(arr2)

[66 99 23 47 54  8 14 52 48 44]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr1+arr2

array([ 67, 101,  26,  51,  59,  14,  21,  60,  57,  54])

52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise

In [ ]:
import numpy as np
arr1=np.arange(10,0,-1)
arr2=np.arange(1,11)
array=arr2-arr1
print(array)

[-9 -7 -5 -3 -1  1  3  5  7  9]


53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`

In [ ]:
arr1=np.random.randint(1,10,size=5)
arr2=np.arange(1,6)
multiple=arr1*arr2
print(multiple)

[ 4  2 18 24 30]


54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`

In [ ]:
arr1=np.arange(2,11,2)
arr2=np.arange(1,6)
division=arr1/arr2
print(division)

[2. 2. 2. 2. 2.]


 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise

In [ ]:
arr1=np.arange(1,6)
arr2=arr1[::-1]
expo=np.power(arr1,arr2)
print(expo)

[ 1 16 27 16  5]


 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
 arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [ ]:
def count_substring(arr,substring):
  return np.char.count(arr,substring).sum()

In [ ]:
arr=np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring='hello'
count_substring(arr,substring)

3

 57. Write a function that extracts uppercase characters from a NumPy array of strings.
 arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
 arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [ ]:
import re

In [ ]:
def uppercase_character(arr):
   uppercase_char=[re.findall(r'[A-Z]',s)for s in arr]
   uppercase_array=np.array(["".join(char)for char in uppercase_char])
   return uppercase_array

In [ ]:
arr=np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase=uppercase_character(arr)
print(uppercase)

['H' 'W' 'OAI' 'GPT']


58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
def replace_substring(arr,old_substring,new_substring):
  return np.char.replace(arr,old_substring,new_substring)

In [ ]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
new_array=replace_substring(arr,'apple','bangan')
print(new_array)

['bangan' 'banana' 'grape' 'pinebangan']


 59. Write a function that concatenates strings in a NumPy array element-wise.
 arr1 = np.array(['Hello', 'World'])
 arr2 = np.array(['Open', 'AI'])

In [ ]:
def concatenate_elementwise(arr1,arr2):
  return np.char.add(arr1,arr2)

In [ ]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
concatenate_elementwise(arr1,arr2)


array(['HelloOpen', 'WorldAI'], dtype='<U9')

 60. Write a function that finds the length of the longest string in a NumPy array.

In [ ]:
def longest_string(arr):
  lengths=np.char.str_len(arr)
  return lengths.max()

In [ ]:
arr=np.array(['Hello', 'World', 'OpenAI', 'GPT'])
longest_string(arr)

6

 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.

In [ ]:
dataset=np.random.randint(1,100,size=100)

In [ ]:
mean=np.mean(dataset)
median=np.median(dataset)
variance=np.var(dataset)
std_dev=np.std(dataset)

In [ ]:
f'mean={mean},median={median},variance={variance},std_dev={std_dev}'

'mean=48.91,median=50.0,variance=920.7619,std_dev=30.344058726544805'

 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

In [ ]:
dataset=np.random.randint(1,100,size=50)
per_25=np.percentile(dataset,25)
per_75=np.percentile(dataset,75)

In [ ]:
f'25%={per_25},75%={per_75}'

'25%=27.25,75%=79.0'

63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function



In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([5,6,7,8,9])
correlation = np.corrcoef(arr1,arr2)
correlation_coefficient=correlation[0,1]
print(correlation_coefficient)

0.9999999999999999


64. Create two matrices and perform matrix multiplication using NumPy's `dot` function

In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8],[9,10],[11,12]])
dot_product=np.dot(arr1,arr2)
print(dot_product)

[[ 58  64]
 [139 154]]


 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.

In [ ]:
dataset=np.random.randint(10,1000,size=50)
pr10=np.percentile(dataset,10)
md50=np.percentile(dataset,50)
pr90=np.percentile(dataset,90)
pr25=np.percentile(dataset,25)
pr75=np.percentile(dataset,75)
f'percentile 10 = {pr10},median 50 = {md50},percentile 90 = {pr90},first quartile ={pr25}, third quartile={pr75}'

'percentile 10 = 104.10000000000001,median 50 = 588.0,percentile 90 = 920.4,first quartile =259.25, third quartile=766.25'

66. Create a NumPy array of integers and find the index of a specific element

In [ ]:
arr=np.array([1,2,3,4,5])
index_to_find=3
index=np.where(arr==index_to_find)[0][0]
F'INDEX OF {index_to_find} is = {index}'

'INDEX OF 3 is = 2'

In [ ]:
indices=np.argwhere(arr==index_to_find)

In [ ]:
indices


array([[2]])

 67. Generate a random NumPy array and sort it in ascending order

In [ ]:
dataset=np.random.randint(1,100,size=10)
sorted_array=np.sort(dataset)
print(sorted_array)

[ 1  3 16 45 45 47 52 58 59 85]



 68. Filter elements >20  in the given NumPy array.
 arr = np.array([12, 25, 6, 42, 8, 30])

In [ ]:
 arr = np.array([12, 25, 6, 42, 8, 30])
 filtered_array=arr[arr>20]
 print(filtered_array)

[25 42 30]


 69. Filter elements which are divisible by 3 from a given NumPy array.
 arr = np.array([1, 5, 8, 12, 15])

In [ ]:
arr = np.array([1, 5, 8, 12, 15])
filtered=arr[arr%3==0]
print(filtered)

[12 15]


 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
 arr = np.array([10, 20, 30, 40, 50])

In [ ]:
 arr = np.array([10, 20, 30, 40, 50])
 filtered=arr[(arr>=20)&(arr<=40)]
 print(filtered)

[20 30 40]


 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
 arr = np.array([1, 2, 3])


In [ ]:
arr=np.array([1, 2, 3])
byte_order=arr.dtype.byteorder
print(byte_order)


=


72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
 arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
print(arr)


[16777216 33554432 50331648]


 73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.
 arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
new_array=arr.astype(arr.dtype.newbyteorder())
print(new_array)
print(arr)

[1 2 3]
[1 2 3]


 74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.
 arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
import sys
arr = np.array([1, 2, 3], dtype=np.int32)
if sys.byteorder=='little':
  new_array=arr.astype(arr.dtype.newbyteorder('>'))
else:
  new_array=arr.astype(arr.dtype.newbyteorder('<'))
print(new_array)
print(arr)



[1 2 3]
[1 2 3]


 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`.
 arr = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder=='=':
  if sys.byteorder=='little':
    byte_swapping_needed=False
  else:
    byte_swapping_needed=True
else:
  byte_swapping_needed=True
print(f'byte swapping needed={byte_swapping_needed}')

byte swapping needed=False


 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [ ]:
arr=np.arange(1,11)
copy_arr=arr.copy()
copy_arr[0]=100
print(arr)
print(copy_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[100   2   3   4   5   6   7   8   9  10]


 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`

In [ ]:
arr=np.random.randint(1,10,size=(3,3))
view_slice=arr[1:,:2]
view_slice[0,0]=100
print(arr)
print(view_slice)

[[  3   3   7]
 [100   8   2]
 [  6   5   4]]
[[100   8]
 [  6   5]]


78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [ ]:
arr=np.arange(1,13).reshape(4,3)
view_b=arr[1:3,0:2]
view_b +=5
print(arr)
print(view_b)

[[ 1  2  3]
 [ 9 10  6]
 [12 13  9]
 [10 11 12]]
[[ 9 10]
 [12 13]]


 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.

In [ ]:
orgin_array=np.arange(1,9).reshape(2,4)
view_reshaped_array=orgin_array.reshape(4,2)
view_reshaped_array[0,0]=100
print(orgin_array)
print(view_reshaped_array)

[[100   2   3   4]
 [  5   6   7   8]]
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [ ]:
arr=np.random.randint(1,10,size=(3,4))
data_copy=arr[arr>5].copy()
data_copy[0]=100
print(arr)
print(data_copy)

[[7 3 3 6]
 [2 2 8 9]
 [6 9 5 8]]
[100   6   8   9   6   9   8]


 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them?

In [ ]:
a=np.random.randint(1,10,size=(3,3))
b=np.random.randint(1,10,size=(3,3))
add=a+b
sub=a-b
print(add)
print(sub)

[[16 13  9]
 [ 8 13 17]
 [ 7  9  8]]
[[ 2  3 -5]
 [-2  5 -1]
 [ 5 -5  6]]


 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication

In [ ]:
c=np.random.randint(1,10,size=(3,2))
d=np.random.randint(1,10,size=(2,4))
mul=np.dot(c,d)
print(mul)

[[28 31 11 33]
 [28 46 17 30]
 [56 82 30 62]]


 83. Create a matrix `E` and find its transpose

In [ ]:
e=np.random.randint(1,10,size=(2,4))
trans=e.T

In [ ]:
trans

array([[9, 2],
       [6, 7],
       [8, 6],
       [6, 7]])

In [ ]:
trans.shape

(4, 2)

 84. Generate a square matrix `F` and compute its determinant

In [ ]:
e=np.random.randint(1,10,size=(2,2))
determinant=np.linalg.det(e)
print(determinant)

-22.000000000000004


 85. Create a square matrix `G` and find its inverse

In [ ]:
G=np.random.randint(1,10,size=(2,2))
inverse=np.linalg.inv(G)
print(inverse)

[[ 0.27272727 -0.18181818]
 [-0.09090909  0.22727273]]
